# Generated by Django 4.2 on 2023-04-21 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('video', models.CharField(max_length=10000000000)),
            ],
        ),
        migrations.CreateModel(
            name='MovieSeries',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('tags', models.CharField(max_length=200)),
                ('img', models.FileField(default='static/img/logo.svg', upload_to='media/images')),
                ('file', models.FileField(upload_to='media/videos')),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('movie', models.CharField(max_length=10000000000)),
                ('img', models.FileField(default='static/img/logo.svg', upload_to='media/payment')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('tags', models.CharField(max_length=200)),
                ('img', models.FileField(default='static/img/logo.svg', upload_to='media/images')),
                ('file', models.FileField(upload_to='media/videos')),
            ],
        ),
        migrations.CreateModel(
            name='Watch_later',
            fields=[
                ('watch_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_id', models.CharField(max_length=1000000000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('hist_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_id', models.CharField(max_length=1000000000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoughtVideoB',
            fields=[
                ('bought_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_id', models.CharField(max_length=1000000000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
