# Generated by Django 4.2 on 2023-04-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('ad_name', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='media/videos')),
            ],
        ),
    ]
