# Generated by Django 4.2 on 2023-04-23 01:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='file',
            field=models.FileField(default='www.youtube.com', upload_to='media/videos'),
        ),
    ]
